title: Rebuild OS - Telemetry stage
actions:
  # Windows Backup & Cloud sync
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\SettingSync'
    value: "DisableSettingSync"
    data: "2"
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\SettingSync'
    value: "DisableSettingSyncUserOverride"
    data: "1"
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\SettingSync'
    value: "DisableSyncOnPaidNetwork"
    data: "1"
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\SettingSync'
    value: "DisableWindowsSettingSync"
    data: "2"
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\SettingSync\Groups\Personalization'
    value: "Enabled"
    data: "0"
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\SettingSync\Groups\BrowserSettings'
    value: "Enabled"
    data: "0"
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\SettingSync\Groups\Credentials'
    value: "Enabled"
    data: "0"
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\SettingSync\Groups\Accessibility'
    value: "Enabled"
    data: "0"
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\SettingSync\Groups\Windows'
    value: "Enabled"
    data: "0"
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\SettingSync'
    value: "SyncPolicy"
    data: "5"
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Messaging'
    value: "AllowMessageSync"
    data: "0"
    type: REG_DWORD

  # Do not show Windows Tips
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\CloudContent'
    value: "DisableSoftLanding"
    data: "1"
    type: REG_DWORD
  - !registryValue: 
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\CloudContent'
    value: "DisableWindowsConsumerFeatures"
    data: "1"
    type: REG_DWORD
  