title: Rebuild OS - Telemetry stage
actions:
  # Windows Backup & Cloud sync
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\SettingSync'
    value: "DisableSettingSync"
    data: "2"
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\SettingSync'
    value: "DisableSettingSyncUserOverride"
    data: "1"
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\SettingSync'
    value: "DisableSyncOnPaidNetwork"
    data: "1"
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\SettingSync'
    value: "DisableWindowsSettingSync"
    data: "2"
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\SettingSync\Groups\Personalization'
    value: "Enabled"
    data: "0"
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\SettingSync\Groups\BrowserSettings'
    value: "Enabled"
    data: "0"
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\SettingSync\Groups\Credentials'
    value: "Enabled"
    data: "0"
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\SettingSync\Groups\Accessibility'
    value: "Enabled"
    data: "0"
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\SettingSync\Groups\Windows'
    value: "Enabled"
    data: "0"
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\SettingSync'
    value: "SyncPolicy"
    data: "5"
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Messaging'
    value: "AllowMessageSync"
    data: "0"
    type: REG_DWORD

  # Do not show Windows Tips
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\CloudContent'
    value: "DisableSoftLanding"
    data: "1"
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\CloudContent'
    value: "DisableWindowsConsumerFeatures"
    data: "1"
    type: REG_DWORD
  - !registryValue: {
      path: 'HKCU\Software\Policies\Microsoft\Windows\CloudContent',
      value: "ConfigureWindowsSpotlight",
      type: REG_DWORD,
      data: "2",
    }
  - !registryValue: {
      path: 'HKCU\Software\Policies\Microsoft\Windows\CloudContent',
      value: "IncludeEnterpriseSpotlight",
      type: REG_DWORD,
      data: "0",
    }
  - !registryValue: {
      path: 'HKCU\Software\Policies\Microsoft\Windows\CloudContent',
      value: "DisableThirdPartySuggestions",
      type: REG_DWORD,
      data: "1",
    }
  - !registryValue: {
      path: 'HKCU\Software\Policies\Microsoft\Windows\CloudContent',
      value: "DisableTailoredExperiencesWithDiagnosticData",
      type: REG_DWORD,
      data: "1",
    }
  - !registryValue: {
      path: 'HKCU\Software\Policies\Microsoft\Windows\CloudContent',
      value: "DisableWindowsSpotlightFeatures",
      type: REG_DWORD,
      data: "1",
    }
  - !registryValue: {
      path: 'HKCU\Software\Policies\Microsoft\Windows\CloudContent',
      value: "DisableWindowsSpotlightWindowsWelcomeExperience",
      type: REG_DWORD,
      data: "1",
    }
  - !registryValue: {
      path: 'HKCU\Software\Policies\Microsoft\Windows\CloudContent',
      value: "DisableWindowsSpotlightOnActionCenter",
      type: REG_DWORD,
      data: "1",
    }
  - !registryValue: {
      path: 'HKCU\Software\Policies\Microsoft\Windows\CloudContent',
      value: "DisableWindowsSpotlightOnSettings",
      type: REG_DWORD,
      data: "1",
    }
  - !registryValue: {
      path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\CloudContent',
      value: "DisableCloudOptimizedContent",
      type: REG_DWORD,
      data: "1",
    }
