title: Rebuild OS - Telemetry stage
actions:
  - !registryValue:
    path: 'HKLM\SYSTEM\CurrentControlSet\Control\Diagnostics\Performance'
    value: "DisableDiagnosticTracing"
    data: "1"
    type: REG_DWORD
  - !service: { name: "DiagTrack", operation: stop, ignoreErrors: true }
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Diagnostics\DiagTrack'
    value: "ShowedToastAtLevel"
    data: "1"
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection'
    value: "AllowTelemetry"
    data: "0"
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection'
    value: "MaxTelemetryAllowed"
    data: "0"
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Policies\DataCollection'
    value: "AllowTelemetry"
    data: "0"
    type: REG_DWORD
  - !registryKey:
    path: 'HKLM\SYSTEM\CurrentControlSet\Control\WMI\Autologger\Diagtrack-Listener'
  - !registryValue:
    path: 'HKLM\SYSTEM\CurrentControlSet\Control\WMI\Autologger\Diagtrack-Listener'
    value: "Start"
    data: "0"
    type: REG_DWORD
  - !cmd: {
      command: 'del "%ProgramData%\Microsoft\Diagnosis\ETLLogs\AutoLogger\DiagTrack*" "%ProgramData%\Microsoft\Diagnosis\ETLLogs\ShutdownLogger\DiagTrack*" > nul 2>&1',
    }
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Privacy'
    value: "TailoredExperiencesWithDiagnosticDataEnabled"
    data: "0"
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Policies\Microsoft\Windows\CloudContent'
    value: "DisableTailoredExperiencesWithDiagnosticData"
    data: "1"
    type: REG_DWORD

  # Disable Performance Track
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\WDI\{9c5a40da-b965-4fc3-8781-88dd50a6299d}'
    value: "ScenarioExecutionEnabled"
    data: "0"
    type: REG_DWORD

  # Disable ADS Info
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\AdvertisingInfo'
    value: "Enabled"
    data: "0"
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\Software\Policies\Microsoft\Windows\AdvertisingInfo'
    value: "DisabledByGroupPolicy"
    data: "1"
    type: REG_DWORD

  # Bluetooth
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\PolicyManager\current\device\Bluetooth'
    value: "AllowAdvertising"
    data: "0"
    type: REG_DWORD