title: Rebuild OS - Telemetry stage
actions:
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\AppV\CEIP'
    value: "CEIPEnable"
    data: "0"
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\SQMClient\Windows'
    value: "CEIPEnable"
    data: "0"
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\PolicyManager\default\System\AllowExperimentation'
    value: "Value"
    data: "0"
    type: REG_DWORD
