title: Rebuild OS - Telemetry stage
actions:
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Speech_OneCore\Settings\OnlineSpeechPrivacy'
    value: 'HasAccepted'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Speech'
    value: 'AllowSpeechModelUpdate'
    data: '0'
    type: REG_DWORD