title: Rebuild OS - Explorer Tweaks
actions:
  #
  # Navigation Pane
  #

  - !run: {
      exe: "reg",
      args: 'add HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\FolderDescriptions\{31C0DD25-9439-4F12-BF41-7FF4EDA38722}\PropertyBag /v ThisPCPolicy /t REG_SZ /d "Hide" /f',
      option: "hide3dobjects",
    }

  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced'
    value: "MultiTaskingAltTabFilter"
    data: "3"
    type: REG_DWORD

  # Disable notifications from microsoft
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced'
    value: "ShowSyncProviderNotifications"
    data: "0"
    type: REG_DWORD

  # Show more information when copying files
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\OperationStatusManager'
    value: "EnthusiastMode"
    data: "1"
    type: REG_DWORD

  # Do not use the search-based method when resolving shell shortcuts
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer'
    value: "NoResolveSearch"
    data: "1"
    type: REG_DWORD

  # Disallow Online Tips
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer'
    value: "AllowOnlineTips"
    data: "1"
    type: REG_DWORD

  # Do not use the tracking-based method when resolving shell shortcuts
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer'
    value: "NoResolveTrack"
    data: "1"
    type: REG_DWORD

  # Launch to This PC instead of Quick access
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced'
    value: "LaunchTo"
    data: "1"
    type: REG_DWORD

  # Show file extensions
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced'
    value: "HideFileExt"
    data: "0"
    type: REG_DWORD

  # Remove 'shortcut' text from shortcuts
  - !registryValue:
    path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\NamingTemplates'
    value: "ShortcutNameTemplate"
    data: '"%s.lnk"'
    type: REG_SZ

  # Disable auto folder discovery
  - !registryValue:
    path: 'HKCU\Software\Classes\Local Settings\Software\Microsoft\Windows\Shell\Bags\AllFolders\Shell'
    value: "FolderType"
    data: "NotSpecified"
    type: REG_SZ

  # Hide Folders from This PC
  - !run: {
      exe: "reg",
      args: 'add HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FolderDescriptions\{31C0DD25-9439-4F12-BF41-7FF4EDA38722}\PropertyBag /v ThisPCPolicy /t REG_SZ /d "Hide" /f',
      option: "hidefoldersthispc",
      runas: "currentUserElevated",
    }
  - !run: {
      exe: "reg",
      args: 'add HKLM\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Explorer\FolderDescriptions\{31C0DD25-9439-4F12-BF41-7FF4EDA38722}\PropertyBag /v ThisPCPolicy /t REG_SZ /d "Hide" /f',
      option: "hidefoldersthispc",
      runas: "currentUserElevated",
    }
  - !run: {
      exe: "reg",
      args: 'add HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FolderDescriptions\{a0c69a99-21c8-4671-8703-7934162fcf1d}\PropertyBag /v ThisPCPolicy /t REG_SZ /d "Hide" /f',
      option: "hidefoldersthispc",
      runas: "currentUserElevated",
    }
  - !run: {
      exe: "reg",
      args: 'add HKLM\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Explorer\FolderDescriptions\{a0c69a99-21c8-4671-8703-7934162fcf1d}\PropertyBag /v ThisPCPolicy /t REG_SZ /d "Hide" /f',
      option: "hidefoldersthispc",
      runas: "currentUserElevated",
    }
  - !run: {
      exe: "reg",
      args: 'add HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FolderDescriptions\{7d83ee9b-2244-4e70-b1f5-5393042af1e4}\PropertyBag /v ThisPCPolicy /t REG_SZ /d "Hide" /f',
      option: "hidefoldersthispc",
      runas: "currentUserElevated",
    }
  - !run: {
      exe: "reg",
      args: 'add HKLM\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Explorer\FolderDescriptions\{7d83ee9b-2244-4e70-b1f5-5393042af1e4}\PropertyBag /v ThisPCPolicy /t REG_SZ /d "Hide" /f',
      option: "hidefoldersthispc",
      runas: "currentUserElevated",
    }
  - !run: {
      exe: "reg",
      args: 'add HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FolderDescriptions\{0ddd015d-b06c-45d5-8c4c-f59713854639}\PropertyBag /v ThisPCPolicy /t REG_SZ /d "Hide" /f',
      option: "hidefoldersthispc",
      runas: "currentUserElevated",
    }
  - !run: {
      exe: "reg",
      args: 'add HKLM\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Explorer\FolderDescriptions\{0ddd015d-b06c-45d5-8c4c-f59713854639}\PropertyBag /v ThisPCPolicy /t REG_SZ /d "Hide" /f',
      option: "hidefoldersthispc",
      runas: "currentUserElevated",
    }
  - !run: {
      exe: "reg",
      args: 'add HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FolderDescriptions\{35286a68-3c57-41a1-bbb1-0eae73d76c95}\PropertyBag /v ThisPCPolicy /t REG_SZ /d "Hide" /f',
      option: "hidefoldersthispc",
      runas: "currentUserElevated",
    }
  - !run: {
      exe: "reg",
      args: 'add HKLM\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Explorer\FolderDescriptions\{35286a68-3c57-41a1-bbb1-0eae73d76c95}\PropertyBag /v ThisPCPolicy /t REG_SZ /d "Hide" /f',
      option: "hidefoldersthispc",
      runas: "currentUserElevated",
    }
  - !run: {
      exe: "reg",
      args: 'add HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FolderDescriptions\{f42ee2d3-909f-4907-8871-4c22fc0bf756}\PropertyBag /v ThisPCPolicy /t REG_SZ /d "Hide" /f',
      option: "hidefoldersthispc",
      runas: "currentUserElevated",
    }
  - !run: {
      exe: "reg",
      args: 'add HKLM\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Explorer\FolderDescriptions\{f42ee2d3-909f-4907-8871-4c22fc0bf756}\PropertyBag /v ThisPCPolicy /t REG_SZ /d "Hide" /f',
      option: "hidefoldersthispc",
      runas: "currentUserElevated",
    }
  - !run: {
      exe: "reg",
      args: 'add HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FolderDescriptions\{B4BFCC3A-DB2C-424C-B029-7FE99A87C641}\PropertyBag /v ThisPCPolicy /t REG_SZ /d "Hide" /f',
      option: "hidefoldersthispc",
      runas: "currentUserElevated",
    }
  - !run: {
      exe: "reg",
      args: 'add HKLM\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Explorer\FolderDescriptions\{B4BFCC3A-DB2C-424C-B029-7FE99A87C641}\PropertyBag /v ThisPCPolicy /t REG_SZ /d "Hide" /f',
      option: "hidefoldersthispc",
      runas: "currentUserElevated",
    }

  # Disable Windows Spotlight
  - !registryValue:
    path: 'HKCU\SOFTWARE\Policies\Microsoft\Windows\CloudContent'
    value: "DisableWindowsSpotlightFeatures"
    data: "1"
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Policies\Microsoft\Windows\CloudContent'
    value: "DisableWindowsSpotlightWindowsWelcomeExperience"
    data: "1"
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Policies\Microsoft\Windows\CloudContent'
    value: "DisableWindowsSpotlightOnActionCenter"
    data: "1"
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Policies\Microsoft\Windows\CloudContent'
    value: "DisableWindowsSpotlightOnSettings"
    data: "1"
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Policies\Microsoft\Windows\CloudContent'
    value: "DisableThirdPartySuggestions"
    data: "1"
    type: REG_DWORD
