title: Rebuild OS - Optional Tweaks
actions:
  - !writeStatus: {
      status: "Disabling Background Apps...",
      option: "backgroundapps",
    }

  - !run: {
      exe: "reg",
      args: 'add HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\BackgroundAccessApplications /v GlobalUserDisabled /t REG_DWORD /d 1 /f',
      option: "backgroundapps",
      runas: "currentUserElevated",
    }
