title: Rebuild OS - AppX removal
actions:
  - !powerShell:
    command: >-
      (Get-AppxPackage).PackageFamilyName | Out-File "$Env:systemdrive\temp.txt"
    runas: currentUserElevated
    wait: true

  - !taskKill: { name: "msteams*", ignoreErrors: true }
  - !writeStatus: { status: "Removing Teams", option: "remove-teams" }
  - !appx: {
      name: "MicrosoftTeams*",
      type: family,
      ignoreErrors: true,
      option: "remove-teams",
    } # Teams
  - !run: {
      exe: "reg",
      args: 'add HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Communications /v ConfigureChatAutoInstall /t REG_DWORD /d 0 /f',
      option: "remove-teams",
    }

  - !writeStatus: { status: "Removing Clipchamp", option: "remove-clipchamp" }
  - !appx: {
      name: "Clipchamp.Clipchamp*",
      type: family,
      ignoreErrors: true,
      option: "remove-clipchamp",
    } # Clipchamp

  - !writeStatus: { status: "Removing Disney+", option: "remove-disney" }
  - !appx: {
      name: "Disney.37853FC22B2CE*",
      type: family,
      ignoreErrors: true,
      option: "remove-disney",
    } # Disney+

  - !writeStatus: { status: "Removing Spotify", option: "remove-spotify" }
  - !appx: {
      name: "SpotifyAB.SpotifyMusic*",
      type: family,
      ignoreErrors: true,
      option: "remove-spotify",
    } # Spotify
  - !appx: {
      name: "*Spotify*",
      type: family,
      ignoreErrors: true,
      option: "remove-spotify",
    } # Another Spotify

  - !writeStatus: { status: "Removing Cortana", option: "remove-cortana" }
  - !appx: {
      name: "Microsoft.549981C3F5F10*",
      type: family,
      ignoreErrors: true,
      option: "remove-cortana",
    } # Cortana

  - !writeStatus: { status: "Removing Legacy Xbox", option: "remove-xbox" }
  - !appx: {
      name: "Microsoft.XboxApp*",
      type: family,
      ignoreErrors: true,
      option: "remove-xbox",
    } # Legacy Xbox Console Companion

  - !writeStatus: {
      status: "Removing Mail and Calendar",
      option: "remove-mail",
    }
  - !appx: {
      name: "microsoft.windowscommunicationsapps*",
      type: family,
      ignoreErrors: true,
      option: "remove-mail",
    } # Mail and Calendar

  - !writeStatus: { status: "Removing Paint 3D", option: "remove-paint3d" }
  - !appx: {
      name: "Microsoft.MSPaint*",
      type: family,
      ignoreErrors: true,
      option: "remove-paint3d",
    } # Paint 3D

  - !writeStatus: { status: "Removing Tips", option: "remove-tips" }
  - !appx: {
      name: "Microsoft.Getstarted*",
      type: family,
      ignoreErrors: true,
      option: "remove-tips",
    } # Tips

  - !writeStatus: { status: "Removing Films & TV", option: "remove-films-tv" }
  - !appx: {
      name: "Microsoft.ZuneVideo*",
      type: family,
      ignoreErrors: true,
      option: "remove-films-tv",
    } # Films & TV

  - !writeStatus: { status: "Removing MS Family", option: "remove-ms-family" }
  - !appx: {
      name: "MicrosoftCorporationII.MicrosoftFamily*",
      type: family,
      ignoreErrors: true,
      option: "remove-ms-family",
    } # MS Family

  - !writeStatus: {
      status: "Removing Mixed Reality",
      option: "remove-mixed-reality",
    }
  - !appx: {
      name: "Microsoft.MixedReality.Portal*",
      type: family,
      ignoreErrors: true,
      option: "remove-mixed-reality",
    } # Mixed Reality

  - !writeStatus: { status: "Removing DevHome", option: "remove-devhome" }
  - !appx: {
      name: "Microsoft.Windows.DevHome*",
      type: family,
      ignoreErrors: true,
      option: "remove-devhome",
    } # DevHome (from win11)

  - !writeStatus: {
      status: "Removing Bing Weather",
      option: "remove-bing-weather",
    }
  - !appx: {
      name: "Microsoft.BingWeather*",
      type: family,
      ignoreErrors: true,
      option: "remove-bing-weather",
    } # Weather

  - !writeStatus: { status: "Removing Bing News", option: "remove-bing-news" }
  - !appx: {
      name: "Microsoft.BingNews*",
      type: family,
      ignoreErrors: true,
      option: "remove-bing-news",
    } # News

  - !writeStatus: { status: "Removing Outlook (new)", option: "remove-outlook" }
  - !appx: {
      name: "Microsoft.OutlookForWindows*",
      type: family,
      ignoreErrors: true,
      option: "remove-outlook",
    } # Outlook (new)

  - !writeStatus: { status: "Removing Get Help", option: "remove-gethelp" }
  - !appx: {
      name: "Microsoft.GetHelp*",
      type: family,
      ignoreErrors: true,
      option: "remove-gethelp",
    } # Get Help

  - !writeStatus: { status: "Removing 3D Viewer", option: "remove-3dviewer" }
  - !appx: {
      name: "Microsoft.Microsoft3DViewer*",
      type: family,
      ignoreErrors: true,
      option: "remove-3dviewer",
    } # 3D Viewer

  - !writeStatus: { status: "Removing Office Hub", option: "remove-officehub" }
  - !appx: {
      name: "Microsoft.MicrosoftOfficeHub*",
      type: family,
      ignoreErrors: true,
      option: "remove-officehub",
    } # Office Hub (Get Office)

  - !writeStatus: { status: "Removing Solitaire", option: "remove-solitaire" }
  - !appx: {
      name: "Microsoft.MicrosoftSolitaireCollection*",
      type: family,
      ignoreErrors: true,
      option: "remove-solitaire",
    } # Solitaire

  - !writeStatus: {
      status: "Removing Sticky Notes",
      option: "remove-sticky-notes",
    }
  - !appx: {
      name: "Microsoft.MicrosoftStickyNotes*",
      type: family,
      ignoreErrors: true,
      option: "remove-sticky-notes",
    } # Sticky Notes

  - !writeStatus: { status: "Removing OneNote", option: "remove-onenote" }
  - !appx: {
      name: "Microsoft.Office.OneNote*",
      type: family,
      ignoreErrors: true,
      option: "remove-onenote",
    } # OneNote

  - !writeStatus: { status: "Removing People", option: "remove-people" }
  - !appx: {
      name: "Microsoft.People*",
      type: family,
      ignoreErrors: true,
      option: "remove-people",
    } # People

  - !writeStatus: {
      status: "Removing Power Automate",
      option: "remove-powerautomate",
    }
  - !appx: {
      name: "Microsoft.PowerAutomateDesktop*",
      type: family,
      ignoreErrors: true,
      option: "remove-powerautomate",
    } # Power Automate Desktop

  - !writeStatus: {
      status: "Removing Snipping Tool",
      option: "remove-snipping-tool",
    }
  - !appx: {
      name: "Microsoft.ScreenSketch*",
      type: family,
      ignoreErrors: true,
      option: "remove-snipping-tool",
    } # Snipping Tool

  # Wallet
  - !writeStatus: { status: "Removing Wallet", option: "remove-wallet" }
  - !appx: {
      name: "Microsoft.Wallet*",
      type: family,
      ignoreErrors: true,
      option: "remove-wallet",
    } # Wallet

  - !writeStatus: { status: "Removing Skype", option: "remove-skype" }
  - !appx: {
      name: "Microsoft.SkypeApp*",
      type: family,
      ignoreErrors: true,
      option: "remove-skype",
    } # Skype

  - !writeStatus: { status: "Removing To-Do", option: "remove-todo" }
  - !appx: {
      name: "Microsoft.Todos*",
      type: family,
      ignoreErrors: true,
      option: "remove-todo",
    } # To-Do

  - !writeStatus: { status: "Removing Alarms & Clock", option: "remove-alarms" }
  - !appx: {
      name: "Microsoft.WindowsAlarms*",
      type: family,
      ignoreErrors: true,
      option: "remove-alarms",
    } # Alarms

  - !writeStatus: { status: "Removing Camera", option: "remove-camera" }
  - !appx: {
      name: "Microsoft.WindowsCamera*",
      type: family,
      ignoreErrors: true,
      option: "remove-camera",
    } # Camera

  - !writeStatus: {
      status: "Removing Feedback Hub",
      option: "remove-feedback-hub",
    }
  - !appx: {
      name: "Microsoft.WindowsFeedbackHub*",
      type: family,
      ignoreErrors: true,
      option: "remove-feedback-hub",
    } # Feedback Hub

  - !writeStatus: { status: "Removing Maps", option: "remove-maps" }
  - !appx: {
      name: "Microsoft.WindowsMaps*",
      type: family,
      ignoreErrors: true,
      option: "remove-maps",
    } # Maps

  - !writeStatus: {
      status: "Removing Sound Recorder",
      option: "remove-sound-recorder",
    }
  - !appx: {
      name: "Microsoft.WindowsSoundRecorder*",
      type: family,
      ignoreErrors: true,
      option: "remove-sound-recorder",
    } # Sound Recorder

  # OneDrive (appx)
  - !writeStatus: { status: "Removing OneDrive (appx)" }
  - !appx: {
      name: "*OneDrive*",
      type: family,
      ignoreErrors: true,
      weight: 10,
      option: "remove-onedrive",
    }

  # Media Player
  - !writeStatus: {
      status: "Removing Music Player",
      option: "remove-musicplayer",
    }
  - !appx: {
      name: "Microsoft.ZuneMusic*",
      type: family,
      ignoreErrors: true,
      weight: 10,
      option: "remove-musicplayer",
    }

  # Your Phone
  - !writeStatus: { status: "Removing Your Phone", option: "remove-your-phone" }
  - !powerShell:
    command: >-
      Get-AppxPackage Microsoft.YourPhone* | Remove-AppxPackage;
      Get-AppxProvisionedPackage -Online | Where-Object { $_.DisplayName -eq 'Microsoft.YourPhone' } | Remove-AppxProvisionedPackage -Online
    runas: currentUserElevated
    option: "remove-your-phone"
    wait: true

  # Prevent provisioned applications from being reinstalled
  # https://learn.microsoft.com/en-us/windows/application-management/remove-provisioned-apps-during-update
  - !writeStatus: { status: "Preventing upgrading appx packages" }
  - !powerShell:
      command: >-
        $a = "$Env:systemdrive\temp.txt";
        (diff (gc "$a") ((Get-AppxPackage).PackageFamilyName)).InputObject | 
        Foreach-Object { New-Item -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Appx\AppxAllUserStore\Deprovisioned" -Name $_ -Force }; 
        Remove-Item "$a" -Force
      runas: currentUserElevated
      wait: true

  - !cmd: {
      command: "del %systemdrive%\\temp.txt /s /q",
      runas: currentUserElevated,
      wait: true,
    }
