title: Rebuild OS - Memory Tweaks
actions:
  # Disable Memory Paging Settings
  - !registryValue:
    path: 'HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management'
    value: "DisablePagingExecutive"
    data: "1"
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management'
    value: "DisablePageCombining"
    data: "1"
    type: REG_DWORD
