title: Rebuild OS - Program Compatibility Assistant
actions:
  - !writeStatus: { status: "Disabling Program Compatibility Assistant" }
  # Program Compatibility Assistant
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\AppCompat'
    value: 'AITEnable'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\AppCompat'
    value: 'AllowTelemetry'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\AppCompat'
    value: 'DisableEngine'
    data: '1'
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\AppCompat'
    value: 'DisableInventory'
    data: '1'
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\AppCompat'
    value: 'DisablePCA'
    data: '1'
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\AppCompat'
    value: 'DisableUAR'
    data: '1'
    type: REG_DWORD