title: Rebuild OS - services
actions:
  - !writeStatus: { status: "Disabling services" }
  - !service: {name: 'lfsvc', operation: change, startup: 4}
  - !service: {name: 'MapsBroker', operation: change, startup: 4}
  - !service: {name: 'OneSyncSvc', operation: change, startup: 4}
  - !service: {name: 'TrkWks', operation: change, startup: 4}
  - !service: {name: 'PcaSvc', operation: change, startup: 4}
  - !service: {name: 'DiagTrack', operation: change, startup: 4}
  - !service: {name: 'WSearch', operation: change, startup: 4}
  - !service: {name: 'diagnosticshub.standardcollector.service', operation: change, startup: 4}
  - !service: {name: 'diagsvc', operation: change, startup: 4}
  - !service: {name: 'WdiServiceHost', operation: change, startup: 4}
  - !service: {name: 'WdiSystemHost', operation: change, startup: 4}
  - !service: {name: 'WerSvc', operation: change, startup: 4} 
  - !service: {name: 'DispBrokerDesktopSvc', operation: change, startup: 4} 
  - !service: {name: 'Telemetry', operation: change, startup: 4}
